version: "3.9"

services:
  backend:
    build: ./stash_and_story
    ports:
      - "8000:8000"
    volumes:
      - ./stash_and_story/db.sqlite3:/app/db.sqlite3

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
