# Generated by Django 4.2.30 on 2026-05-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
    ]
